"""ai_conversations.meta for CLI session binding

Revision ID: 1957a1dde7b1
Revises: 59ee24821fcc
Create Date: 2026-09-09 14:32:04.698486

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1957a1dde7b1'
down_revision: str | Sequence[str] | None = '59ee24821fcc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_conversations', 'meta')
    # ### end Alembic commands ###
