"""track c: plan_versions, integration_events, embeddings

Revision ID: 8ba01e740630
Revises: 770163381526
Create Date: 2026-09-09 05:34:35.628908

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8ba01e740630'
down_revision: str | Sequence[str] | None = '770163381526'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_embedding_entity')
    )
    op.create_index(op.f('ix_embeddings_user_id'), 'embeddings', ['user_id'], unique=False)
    op.create_table('integration_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_integration_event')
    )
    op.create_index(op.f('ix_integration_events_metric'), 'integration_events', ['metric'], unique=False)
    op.create_index(op.f('ix_integration_events_source'), 'integration_events', ['source'], unique=False)
    op.create_index(op.f('ix_integration_events_user_id'), 'integration_events', ['user_id'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_versions_entity_id'), 'plan_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_plan_versions_entity_type'), 'plan_versions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_plan_versions_user_id'), 'plan_versions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_versions_user_id'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_entity_type'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_entity_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_integration_events_user_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_source'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_metric'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_embeddings_user_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
