"""ai_messages.meta for persisted traces

Revision ID: 9b095f7992a1
Revises: 1957a1dde7b1
Create Date: 2026-09-09 14:48:09.662201

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b095f7992a1'
down_revision: str | Sequence[str] | None = '1957a1dde7b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'meta')
    # ### end Alembic commands ###
