"""food_logs.eaten_at

Revision ID: d4704ca8c039
Revises: e829a380be71
Create Date: 2026-09-09 23:35:05.703423

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd4704ca8c039'
down_revision: str | Sequence[str] | None = 'e829a380be71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_logs', 'eaten_at')
    # ### end Alembic commands ###
