"""meal_plans.time_minutes

Revision ID: e829a380be71
Revises: 9b095f7992a1
Create Date: 2026-09-09 14:55:48.892432

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e829a380be71'
down_revision: str | Sequence[str] | None = '9b095f7992a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'time_minutes')
    # ### end Alembic commands ###
